# Issue 10437: f2py and sage : impossible to create a .so lib ?

archive/issues_010384.json:
```json
{
    "body": "I'm trying to install a module which uses fortran code. The installation of that module perfectly works with \npython setup.py install\n\nBut the fortran compilation with sage fails :\nsage setup.py install\nwith the error :\n undefined reference to `MAIN__'\n\n\nIn fact, a \"mrcwaf.so\" file should be created, which is a lib file containing the Fortran code, but with the sage line code the compilation runs as if it wasn't a lib and searches for a MAIN.\n\nI think the gcc compilation line made by sage hasn't the correct options.\n\nI attach the messages from the classic python compiling and the sage compilations errors.\n\nI'm using python2.6, sage 4.5.2, gcc 4.4.4, f2py 2 and numpy 1.3.0 with fedora 12\n\nHere is the program I want to install :\n\nhttp://sourceforge.net/projects/mrcwa/\n\nPS : I succeed to install mrcwa in sage by first compiling the fortran with the python line which creates the mrcwaf.so file. And then,  the compilation of the program with sage sees this mrcwaf.so  and copies it in the sage tree.\n\n\n\nAssignee: jason, jkantor\n\nKeywords: f2py compilation lib\n\nReviewer: Jeroen Demeyer\n\nResolution: worksforme\n\nIssue created by migration from https://trac.sagemath.org/ticket/10437\n\n",
    "closed_at": "2012-08-23T12:57:10Z",
    "created_at": "2010-12-06T14:46:01Z",
    "labels": [
        "component: numerical",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-duplicate/invalid/wontfix",
    "title": "f2py and sage : impossible to create a .so lib ?",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/10437",
    "user": "https://trac.sagemath.org/admin/accounts/users/Christyves"
}
```
I'm trying to install a module which uses fortran code. The installation of that module perfectly works with 
python setup.py install

But the fortran compilation with sage fails :
sage setup.py install
with the error :
 undefined reference to `MAIN__'


In fact, a "mrcwaf.so" file should be created, which is a lib file containing the Fortran code, but with the sage line code the compilation runs as if it wasn't a lib and searches for a MAIN.

I think the gcc compilation line made by sage hasn't the correct options.

I attach the messages from the classic python compiling and the sage compilations errors.

I'm using python2.6, sage 4.5.2, gcc 4.4.4, f2py 2 and numpy 1.3.0 with fedora 12

Here is the program I want to install :

http://sourceforge.net/projects/mrcwa/

PS : I succeed to install mrcwa in sage by first compiling the fortran with the python line which creates the mrcwaf.so file. And then,  the compilation of the program with sage sees this mrcwaf.so  and copies it in the sage tree.



Assignee: jason, jkantor

Keywords: f2py compilation lib

Reviewer: Jeroen Demeyer

Resolution: worksforme

Issue created by migration from https://trac.sagemath.org/ticket/10437





---

archive/issue_comments_128744.json:
```json
{
    "body": "Attachment [compilation_msg](tarball://root/attachments/some-uuid/ticket10437/compilation_msg) by Christyves created at 2010-12-06 14:47:28",
    "created_at": "2010-12-06T14:47:28Z",
    "issue": "https://github.com/sagemath/sagetest/issues/10437",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/10437#issuecomment-128744",
    "user": "https://trac.sagemath.org/admin/accounts/users/Christyves"
}
```

Attachment [compilation_msg](tarball://root/attachments/some-uuid/ticket10437/compilation_msg) by Christyves created at 2010-12-06 14:47:28



---

archive/issue_comments_128745.json:
```json
{
    "body": "<a id='comment:1'></a>I think this problem has been solved, but since the error report is very unclear I cannot tell for sure, so I'm going to close this anyway.",
    "created_at": "2012-08-23T12:57:10Z",
    "issue": "https://github.com/sagemath/sagetest/issues/10437",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/10437#issuecomment-128745",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:1'></a>I think this problem has been solved, but since the error report is very unclear I cannot tell for sure, so I'm going to close this anyway.



---

archive/issue_comments_128746.json:
```json
{
    "body": "Changing reviewer from \"\" to \"Jeroen Demeyer\"",
    "created_at": "2012-08-23T12:57:10Z",
    "issue": "https://github.com/sagemath/sagetest/issues/10437",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/10437#issuecomment-128746",
    "user": "https://github.com/jdemeyer"
}
```

Changing reviewer from "" to "Jeroen Demeyer"



---

archive/issue_events_026734.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2012-08-23T12:57:10Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/10437",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/10437#event-26734"
}
```



---

archive/issue_comments_128747.json:
```json
{
    "body": "Resolution: worksforme",
    "created_at": "2012-08-23T12:57:10Z",
    "issue": "https://github.com/sagemath/sagetest/issues/10437",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/10437#issuecomment-128747",
    "user": "https://github.com/jdemeyer"
}
```

Resolution: worksforme



---

archive/issue_events_026735.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2012-08-23T12:57:10Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sagetest/issues/10437",
    "milestone": "sage-duplicate/invalid/wontfix",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/10437#event-26735"
}
```
