# Issue 28523: py3: imagemagick,internet,latex str vs bytes doctests failures

Issue created by migration from https://trac.sagemath.org/ticket/28760

Original creator: slabbe

Original creation time: 2019-11-19 08:47:20


```
sage -t --optional=sage,optional,external src/sage/coding/databases.py src/sage/repl/load.py src/sage/misc/latex.py  
```


gives


```
too many failed tests, not using stored timings
Running doctests with ID 2019-11-19-09-45-34-de2336ec.
Git branch: develop
Using --optional=4ti2,cbc,ccache,cryptominisat,dot2tex,e_antic,external,glucose,latte_int,lidia,lrslib,memlimit,normaliz,notedown,openssl,pandoc_attributes,pycosat,pynormaliz,rst2ipynb,sage,sagenb
External software to be detected: cplex,ffmpeg,graphviz,gurobi,imagemagick,internet,latex,macaulay2,magma,maple,mathematica,matlab,octave,pandoc,scilab
Doctesting 3 files.
sage -t src/sage/coding/databases.py
**********************************************************************
File "src/sage/coding/databases.py", line 137, in sage.coding.databases.best_linear_code_in_codetables_dot_de
Failed example:
    L = codes.databases.best_linear_code_in_codetables_dot_de(72, 36, GF(2))    # optional - internet
Exception raised:
    Traceback (most recent call last):
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1123, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.coding.databases.best_linear_code_in_codetables_dot_de[0]>", line 1, in <module>
        L = codes.databases.best_linear_code_in_codetables_dot_de(Integer(72), Integer(36), GF(Integer(2)))    # optional - internet
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/coding/databases.py", line 174, in best_linear_code_in_codetables_dot_de
        i = s.find("<PRE>")
    TypeError: argument should be integer or bytes-like object, not 'str'
**********************************************************************
File "src/sage/coding/databases.py", line 138, in sage.coding.databases.best_linear_code_in_codetables_dot_de
Failed example:
    print(L)                                                                    # optional - internet
Exception raised:
    Traceback (most recent call last):
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1123, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.coding.databases.best_linear_code_in_codetables_dot_de[1]>", line 1, in <module>
        print(L)                                                                    # optional - internet
    NameError: name 'L' is not defined
**********************************************************************
1 item had failures:
   2 of   3 in sage.coding.databases.best_linear_code_in_codetables_dot_de
    [7 tests, 2 failures, 1.17 s]
sage -t src/sage/repl/load.py
**********************************************************************
File "src/sage/repl/load.py", line 157, in sage.repl.load.load
Failed example:
    sage.repl.load.load('https://github.com/jasongrout/minimum_rank/raw/minimum_rank_1_0_0/minrank.py', globals())  # optional - internet
Exception raised:
    Traceback (most recent call last):
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1123, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.load.load[16]>", line 1, in <module>
        sage.repl.load.load('https://github.com/jasongrout/minimum_rank/raw/minimum_rank_1_0_0/minrank.py', globals())  # optional - internet
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/repl/load.py", line 235, in load
        filename = get_remote_file(filename, verbose=False)
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/misc/remote_file.py", line 49, in get_remote_file
        f.write(content.read())
    TypeError: write() argument must be str, not bytes
**********************************************************************
1 item had failures:
   1 of  36 in sage.repl.load.load
    [44 tests, 1 failure, 1.14 s]
sage -t src/sage/misc/latex.py
**********************************************************************
File "src/sage/misc/latex.py", line 1085, in sage.misc.latex.Latex.?
Failed example:
    latex.eval("\ThisIsAnInvalidCommand", {}) # optional -- ImageMagick
Exception raised:
    Traceback (most recent call last):
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1123, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.latex.Latex.?[1]>", line 1, in <module>
        latex.eval("\ThisIsAnInvalidCommand", {}) # optional -- ImageMagick
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/misc/latex.py", line 1114, in eval
        O.write(str_to_bytes(x, encoding='utf-8'))
    TypeError: write() argument must be str, not bytes
**********************************************************************
1 item had failures:
   1 of   3 in sage.misc.latex.Latex.?
    [309 tests, 1 failure, 1.20 s]
----------------------------------------------------------------------
sage -t src/sage/coding/databases.py  # 2 doctests failed
sage -t src/sage/repl/load.py  # 1 doctest failed
sage -t src/sage/misc/latex.py  # 1 doctest failed
----------------------------------------------------------------------
Total time for all tests: 3.9 seconds
    cpu time: 1.3 seconds
    cumulative wall time: 3.5 seconds
External software detected for doctesting: imagemagick,internet,latex
```



---

Comment by chapoton created at 2019-11-19 10:50:01

src/sage/misc/persist.pyx is fixed in #28761


---

Comment by chapoton created at 2019-11-19 12:57:52

src/sage/repl/load.py is almost fixed by #28761 too


---

Comment by chapoton created at 2019-11-19 14:53:07

Here is a fix for databases
----
New commits:


---

Comment by slabbe created at 2019-11-27 15:14:41

Spliting this ticket and moving the other issues to #28808


---

Comment by slabbe created at 2019-11-27 15:15:02

Changing status from new to needs_review.


---

Comment by slabbe created at 2019-11-27 15:15:29

Changing status from needs_review to positive_review.


---

Comment by vbraun created at 2019-11-29 23:57:37

Resolution: fixed
