# Issue 29251: plot3d method of Graphics objects broken with threejs

archive/issues_029014.json:
```json
{
    "body": "As reported in https://ask.sagemath.org/question/50051/, 3d objects constructed by the method `plot3d()` of class `Graphics` do not display properly with `threejs`. A minimal example is\n\n```\nsage: g = plot(sin(x), (x, 0, 2*pi))\nsage: g.plot3d()\n/home/eric/sage/9.1.develop/local/lib/python3.7/site-packages/sage/repl/rich_output/display_manager.py:592: \nRichReprWarning: Exception in _rich_repr_ while displaying object: \n'Line' object has no attribute 'all'\n  RichReprWarning,\n```\nNote that\n\n```\nsage: show(g.plot3d(), viewer='jmol')\nLaunched jmol viewer for Graphics3d Object\n```\nworks well.\nBesides, if one change the value of the argument `z` from `0` (the default) to `2`:\n\n```\nsage: g.plot3d(z=2)\nLaunched html viewer for Graphics3d Object\n```\none does not get any error message but a wrong threejs display: the curve is located at z=-2 instead of z=2.\n\nDepends on #29227\n\n**CC:**  @paulmasson\n\n**Keywords:** graphics, plot3d, threejs\n\n**Reviewer:** Paul Masson, Eric Gourgoulhon\n\nIssue created by migration from https://trac.sagemath.org/ticket/29251\n\n",
    "closed_at": "2020-03-25T19:38:46Z",
    "created_at": "2020-02-27T12:51:07Z",
    "labels": [
        "component: graphics",
        "bug",
        "duplicate"
    ],
    "title": "plot3d method of Graphics objects broken with threejs",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/29251",
    "user": "https://github.com/egourgoulhon"
}
```
As reported in https://ask.sagemath.org/question/50051/, 3d objects constructed by the method `plot3d()` of class `Graphics` do not display properly with `threejs`. A minimal example is

```
sage: g = plot(sin(x), (x, 0, 2*pi))
sage: g.plot3d()
/home/eric/sage/9.1.develop/local/lib/python3.7/site-packages/sage/repl/rich_output/display_manager.py:592: 
RichReprWarning: Exception in _rich_repr_ while displaying object: 
'Line' object has no attribute 'all'
  RichReprWarning,
```
Note that

```
sage: show(g.plot3d(), viewer='jmol')
Launched jmol viewer for Graphics3d Object
```
works well.
Besides, if one change the value of the argument `z` from `0` (the default) to `2`:

```
sage: g.plot3d(z=2)
Launched html viewer for Graphics3d Object
```
one does not get any error message but a wrong threejs display: the curve is located at z=-2 instead of z=2.

Depends on #29227

**CC:**  @paulmasson

**Keywords:** graphics, plot3d, threejs

**Reviewer:** Paul Masson, Eric Gourgoulhon

Issue created by migration from https://trac.sagemath.org/ticket/29251





---

archive/issue_comments_461544.json:
```json
{
    "body": "**Dependencies:** #29227",
    "created_at": "2020-03-19T21:16:45Z",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29251#issuecomment-461544",
    "user": "https://github.com/paulmasson"
}
```

**Dependencies:** #29227



---

archive/issue_comments_461545.json:
```json
{
    "body": "<a id='comment:2'></a>\nWill be fixed by #29227",
    "created_at": "2020-03-19T21:16:45Z",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29251#issuecomment-461545",
    "user": "https://github.com/paulmasson"
}
```

<a id='comment:2'></a>
Will be fixed by #29227



---

archive/issue_comments_461546.json:
```json
{
    "body": "**Reviewer:** Paul Masson",
    "created_at": "2020-03-22T21:51:11Z",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29251#issuecomment-461546",
    "user": "https://github.com/paulmasson"
}
```

**Reviewer:** Paul Masson



---

archive/issue_events_260189.json:
```json
{
    "actor": "https://github.com/paulmasson",
    "created_at": "2020-03-22T21:51:11Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29251#event-260189"
}
```



---

archive/issue_events_260190.json:
```json
{
    "actor": "https://github.com/paulmasson",
    "created_at": "2020-03-22T21:51:11Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "milestone": "sage-9.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29251#event-260190"
}
```



---

archive/issue_comments_461547.json:
```json
{
    "body": "**Changing reviewer** from \"Paul Masson\" to \"Paul Masson, Eric Gourgoulhon\".",
    "created_at": "2020-03-23T08:02:29Z",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29251#issuecomment-461547",
    "user": "https://github.com/egourgoulhon"
}
```

**Changing reviewer** from "Paul Masson" to "Paul Masson, Eric Gourgoulhon".



---

archive/issue_events_260191.json:
```json
{
    "actor": "https://github.com/egourgoulhon",
    "created_at": "2020-03-23T08:02:29Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29251#event-260191"
}
```



---

archive/issue_events_260192.json:
```json
{
    "actor": "https://github.com/egourgoulhon",
    "created_at": "2020-03-23T08:02:29Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29251#event-260192"
}
```



---

archive/issue_comments_461548.json:
```json
{
    "body": "<a id='comment:4'></a>\nI confirm that the issue reported here is fixed by #29227.",
    "created_at": "2020-03-23T08:02:29Z",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29251#issuecomment-461548",
    "user": "https://github.com/egourgoulhon"
}
```

<a id='comment:4'></a>
I confirm that the issue reported here is fixed by #29227.



---

archive/issue_events_260193.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-03-25T19:38:46Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29251#event-260193"
}
```



---

archive/issue_events_260194.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-03-25T19:38:46Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29251#event-260194"
}
```



---

archive/issue_events_260195.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-03-25T19:38:46Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29251",
    "label": "duplicate",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29251#event-260195"
}
```
