# Issue 33170: Update doctests for compatibility with ipython 8.x

archive/issues_032933.json:
```json
{
    "assignees": [],
    "body": "Besides trivial output format changes, the only breakage seems to be tracebacks no longer showing cython source code\n\n```\n**********************************************************************\nFile \"src/sage/repl/interpreter.py\", line 77, in sage.repl.interpreter\nFailed example:\n    print(\"dummy line\"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test\nExpected:\n    dummy line\n    ...\n    ZeroDivisionError...Traceback (most recent call last)\n    <ipython-input-...> in <module>...\n    ----> 1 Integer(1)/Integer(0)\n    .../sage/rings/integer.pyx in sage.rings.integer.Integer...div...\n    ...\n    -> ...                  raise ZeroDivisionError(\"rational division by zero\")\n       ...            x = <Rational> Rational.__new__(Rational)\n       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)\n    <BLANKLINE>\n    ZeroDivisionError: rational division by zero\nGot:\n    dummy line\n    ---------------------------------------------------------------------------\n    ZeroDivisionError                         Traceback (most recent call last)\n    Input In [1], in <module>\n    ----> 1 Integer(1)/Integer(0)\n    <BLANKLINE>\n    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13679)()\n    <BLANKLINE>\n    ZeroDivisionError: rational division by zero\n**********************************************************************\n```\nThe update itself requires a bunch of new dependencies\n\nCC:  @mkoeppe @kiwifb @collares\n\nBranch/Commit: **[`4d2b53f`](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)**\n\nReviewer: **Gonzalo Tornar\u00eda**\n\nAuthor: **Antonio Rojas**\n\nComponent: **packages: standard**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/33170_\n\n",
    "closed_at": "2022-03-21T23:34:36Z",
    "created_at": "2022-01-14T19:53:07Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20packages%3A%20standard",
        "https://github.com/sagemath/sage/labels/p%3A%203%20%E2%80%93%20major",
        "https://github.com/sagemath/sage/labels/enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-9.6",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "Update doctests for compatibility with ipython 8.x",
    "type": "issue",
    "updated_at": "2022-03-21T23:34:36Z",
    "url": "https://github.com/sagemath/sage/issues/33170",
    "user": "https://github.com/antonio-rojas"
}
```
Besides trivial output format changes, the only breakage seems to be tracebacks no longer showing cython source code

```
**********************************************************************
File "src/sage/repl/interpreter.py", line 77, in sage.repl.interpreter
Failed example:
    print("dummy line"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test
Expected:
    dummy line
    ...
    ZeroDivisionError...Traceback (most recent call last)
    <ipython-input-...> in <module>...
    ----> 1 Integer(1)/Integer(0)
    .../sage/rings/integer.pyx in sage.rings.integer.Integer...div...
    ...
    -> ...                  raise ZeroDivisionError("rational division by zero")
       ...            x = <Rational> Rational.__new__(Rational)
       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
Got:
    dummy line
    ---------------------------------------------------------------------------
    ZeroDivisionError                         Traceback (most recent call last)
    Input In [1], in <module>
    ----> 1 Integer(1)/Integer(0)
    <BLANKLINE>
    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13679)()
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
**********************************************************************
```
The update itself requires a bunch of new dependencies

CC:  @mkoeppe @kiwifb @collares

Branch/Commit: **[`4d2b53f`](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)**

Reviewer: **Gonzalo Tornar√≠a**

Author: **Antonio Rojas**

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/33170_





---

archive/issue_events_458622.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-01-14T19:53:07Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "milestone_number": null,
    "milestone_title": "sage-9.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458622"
}
```



---

archive/issue_events_458623.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-01-14T19:53:07Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "label": "https://github.com/sagemath/sage/labels/p%3A%203%20%E2%80%93%20major",
    "label_color": "ffbb00",
    "label_name": "p: 3 \u2013 major",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458623"
}
```



---

archive/issue_comments_536126.json:
```json
{
    "body": "Branch: **[u/arojas/update_to_ipython_8](https://github.com/sagemath/sagetrac-mirror/tree/u/arojas/update_to_ipython_8)**",
    "created_at": "2022-01-14T19:54:09Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536126",
    "user": "https://github.com/antonio-rojas"
}
```

Branch: **[u/arojas/update_to_ipython_8](https://github.com/sagemath/sagetrac-mirror/tree/u/arojas/update_to_ipython_8)**



---

archive/issue_events_458624.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-01-14T19:57:54Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "label": "https://github.com/sagemath/sage/labels/enhancement",
    "label_color": "696969",
    "label_name": "enhancement",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458624"
}
```



---

archive/issue_comments_536127.json:
```json
{
    "body": "Commit: **[`c373551`](https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70)**",
    "created_at": "2022-01-14T19:57:54Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536127",
    "user": "https://github.com/antonio-rojas"
}
```

Commit: **[`c373551`](https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70)**



---

archive/issue_events_458625.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-01-14T19:57:54Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20packages%3A%20standard",
    "label_color": "000080",
    "label_name": "c: packages: standard",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458625"
}
```



---

archive/issue_events_458626.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-01-14T19:57:54Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "milestone_number": null,
    "milestone_title": "sage-9.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458626"
}
```



---

archive/issue_events_458627.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-01-14T19:57:54Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "milestone_number": null,
    "milestone_title": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458627"
}
```



---

archive/issue_comments_536128.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1 +1,33 @@\n+Besides trivial output format changes, the only breakage seems to be tracebacks no longer showing cython source code\n \n+```\n+**********************************************************************\n+File \"src/sage/repl/interpreter.py\", line 77, in sage.repl.interpreter\n+Failed example:\n+    print(\"dummy line\"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test\n+Expected:\n+    dummy line\n+    ...\n+    ZeroDivisionError...Traceback (most recent call last)\n+    <ipython-input-...> in <module>...\n+    ----> 1 Integer(1)/Integer(0)\n+    .../sage/rings/integer.pyx in sage.rings.integer.Integer...div...\n+    ...\n+    -> ...                  raise ZeroDivisionError(\"rational division by zero\")\n+       ...            x = <Rational> Rational.__new__(Rational)\n+       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)\n+    <BLANKLINE>\n+    ZeroDivisionError: rational division by zero\n+Got:\n+    dummy line\n+    ---------------------------------------------------------------------------\n+    ZeroDivisionError                         Traceback (most recent call last)\n+    Input In [1], in <module>\n+    ----> 1 Integer(1)/Integer(0)\n+    <BLANKLINE>\n+    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13679)()\n+    <BLANKLINE>\n+    ZeroDivisionError: rational division by zero\n+**********************************************************************\n+```\n+The update itself requires a bunch of new dependencies\n``````\n",
    "created_at": "2022-01-14T19:57:54Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536128",
    "user": "https://github.com/antonio-rojas"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1 +1,33 @@
+Besides trivial output format changes, the only breakage seems to be tracebacks no longer showing cython source code
 
+```
+**********************************************************************
+File "src/sage/repl/interpreter.py", line 77, in sage.repl.interpreter
+Failed example:
+    print("dummy line"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test
+Expected:
+    dummy line
+    ...
+    ZeroDivisionError...Traceback (most recent call last)
+    <ipython-input-...> in <module>...
+    ----> 1 Integer(1)/Integer(0)
+    .../sage/rings/integer.pyx in sage.rings.integer.Integer...div...
+    ...
+    -> ...                  raise ZeroDivisionError("rational division by zero")
+       ...            x = <Rational> Rational.__new__(Rational)
+       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)
+    <BLANKLINE>
+    ZeroDivisionError: rational division by zero
+Got:
+    dummy line
+    ---------------------------------------------------------------------------
+    ZeroDivisionError                         Traceback (most recent call last)
+    Input In [1], in <module>
+    ----> 1 Integer(1)/Integer(0)
+    <BLANKLINE>
+    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13679)()
+    <BLANKLINE>
+    ZeroDivisionError: rational division by zero
+**********************************************************************
+```
+The update itself requires a bunch of new dependencies
``````




---

archive/issue_comments_536129.json:
```json
{
    "body": "<div id=\"comment:2\"></div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70\"><code>c373551</code></a></td><td><code>Fix tests expected output to match ipython 8</code></td></tr></table>\n",
    "created_at": "2022-01-14T19:57:54Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536129",
    "user": "https://github.com/antonio-rojas"
}
```

<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70"><code>c373551</code></a></td><td><code>Fix tests expected output to match ipython 8</code></td></tr></table>




---

archive/issue_comments_536130.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">comment:3</div>\n\n(Thank you for maintaining Sage on archlinux! Just updated to 9.5)\n\nI think it might be a good idea to document somewhere how to disable the autoformatter and suggestion in IPython 8, which are enabled by default (also useful for people who haven't updated to IPython 8 and want to enable these features)\n\n```\nshell = get_ipython()\nshell.autoformatter = None\nshell.pt_app.auto_suggest = None\n# from prompt_toolkit.auto_suggest import AutoSuggestFromHistory\n# shell.autoformatter = \"black\"\n# shell.pt_app.auto_suggest = AutoSuggestFromHistory()\n```",
    "created_at": "2022-01-30T22:02:28Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536130",
    "user": "https://github.com/8d1h"
}
```

<div id="comment:3" align="right">comment:3</div>

(Thank you for maintaining Sage on archlinux! Just updated to 9.5)

I think it might be a good idea to document somewhere how to disable the autoformatter and suggestion in IPython 8, which are enabled by default (also useful for people who haven't updated to IPython 8 and want to enable these features)

```
shell = get_ipython()
shell.autoformatter = None
shell.pt_app.auto_suggest = None
# from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
# shell.autoformatter = "black"
# shell.pt_app.auto_suggest = AutoSuggestFromHistory()
```



---

archive/issue_comments_536131.json:
```json
{
    "body": "<div id=\"comment:4\" align=\"right\">comment:4</div>\n\nAccording to release notes, IPython 8 is still in alpha/beta stage,  https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-0\n\nSo I don't think we should do the actual update soon. Perhaps open a separate ticket for the update and only put doctest adjustments on the present ticket?",
    "created_at": "2022-01-30T22:09:51Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536131",
    "user": "https://github.com/mkoeppe"
}
```

<div id="comment:4" align="right">comment:4</div>

According to release notes, IPython 8 is still in alpha/beta stage,  https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-0

So I don't think we should do the actual update soon. Perhaps open a separate ticket for the update and only put doctest adjustments on the present ticket?



---

archive/issue_comments_536132.json:
```json
{
    "body": "<div id=\"comment:5\" align=\"right\">comment:5</div>\n\nReplying to [@8d1h](#comment:3):\n> I think it might be a good idea to document somewhere how to disable the autoformatter and suggestion in IPython 8, which are enabled by default\n\nIn my opinion, we should actually disable these features by default. They change Sage's behavior in a potentially very irritating way and many users won't even know what is causing it and which keywords to search for to change it back.",
    "created_at": "2022-02-01T07:14:48Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536132",
    "user": "https://github.com/yyyyx4"
}
```

<div id="comment:5" align="right">comment:5</div>

Replying to [@8d1h](#comment:3):
> I think it might be a good idea to document somewhere how to disable the autoformatter and suggestion in IPython 8, which are enabled by default

In my opinion, we should actually disable these features by default. They change Sage's behavior in a potentially very irritating way and many users won't even know what is causing it and which keywords to search for to change it back.



---

archive/issue_comments_536133.json:
```json
{
    "body": "<div id=\"comment:6\" align=\"right\">comment:6</div>\n\nI filed https://github.com/alexmojaki/stack_data/issues/21 to address the lack of Cython source code in tracebacks. I also asked for a clarification with regards to IPython 8's stability and, [according to the developer](https://github.com/ipython/ipython/pull/13461#issuecomment-1035560431), IPython 8 is a stable release; the notice in the release notes about it being alpha/beta quality just wasn't removed soon enough.",
    "created_at": "2022-02-11T21:45:36Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536133",
    "user": "https://github.com/collares"
}
```

<div id="comment:6" align="right">comment:6</div>

I filed https://github.com/alexmojaki/stack_data/issues/21 to address the lack of Cython source code in tracebacks. I also asked for a clarification with regards to IPython 8's stability and, [according to the developer](https://github.com/ipython/ipython/pull/13461#issuecomment-1035560431), IPython 8 is a stable release; the notice in the release notes about it being alpha/beta quality just wasn't removed soon enough.



---

archive/issue_comments_536134.json:
```json
{
    "body": "<div id=\"comment:7\" align=\"right\">comment:7</div>\n\nAlthough I won't have time to test it until next week, upstream just reported that Cython source code should now appear on tracebacks if Python package `stack_data` is updated to 0.2.0.",
    "created_at": "2022-02-14T19:01:28Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536134",
    "user": "https://github.com/collares"
}
```

<div id="comment:7" align="right">comment:7</div>

Although I won't have time to test it until next week, upstream just reported that Cython source code should now appear on tracebacks if Python package `stack_data` is updated to 0.2.0.



---

archive/issue_comments_536135.json:
```json
{
    "body": "<div id=\"comment:8\"></div>\n\nBranch pushed to git repo; I updated commit sha1. New commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231\"><code>a90a314</code></a></td><td><code>Fix cython source test output for ipython 8 syntax</code></td></tr></table>\n",
    "created_at": "2022-02-14T19:21:22Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536135",
    "user": "https://github.com/sagetrac-git"
}
```

<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231"><code>a90a314</code></a></td><td><code>Fix cython source test output for ipython 8 syntax</code></td></tr></table>




---

archive/issue_comments_536136.json:
```json
{
    "body": "Changed commit from **[`c373551`](https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70)** to **[`a90a314`](https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231)**",
    "created_at": "2022-02-14T19:21:22Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536136",
    "user": "https://github.com/sagetrac-git"
}
```

Changed commit from **[`c373551`](https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70)** to **[`a90a314`](https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231)**



---

archive/issue_comments_536137.json:
```json
{
    "body": "<div id=\"comment:9\" align=\"right\">comment:9</div>\n\nReplying to [@collares](#comment:7):\n> Although I won't have time to test it until next week, upstream just reported that Cython source code should now appear on tracebacks if Python package `stack_data` is updated to 0.2.0.\n\nConfirmed, thanks. Test still failed because of slightly different syntax, should be fixed now.",
    "created_at": "2022-02-14T19:22:42Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536137",
    "user": "https://github.com/antonio-rojas"
}
```

<div id="comment:9" align="right">comment:9</div>

Replying to [@collares](#comment:7):
> Although I won't have time to test it until next week, upstream just reported that Cython source code should now appear on tracebacks if Python package `stack_data` is updated to 0.2.0.

Confirmed, thanks. Test still failed because of slightly different syntax, should be fixed now.



---

archive/issue_comments_536138.json:
```json
{
    "body": "<div id=\"comment:10\" align=\"right\">comment:10</div>\n\nIn addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:\n\n```\n$ sage -t src/sage/repl/interpreter.py src/sage/repl/interface_magic.py \nRunning doctests with ID 2022-02-28-15-14-42-bbd14288.\nUsing --optional=build,pip,sage,sage_spkg,void\nFeatures to be detected: 4ti2,benzene,bliss,buckygen,conway_polynomials,csdp,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_jones_numfield,database_knotinfo,dvipng,graphviz,imagemagick,jupymake,kenzo,latte_int,lrslib,mcqd,meataxe,pandoc,pdf2svg,plantri,pynormaliz,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.plot,sage.rings.number_field,sage.rings.real_double,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,sphinx,tdlib\nDoctesting 2 files.\nsage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interpreter.py\n**********************************************************************\nFile \"src/sage/repl/interpreter.py\", line 425, in sage.repl.interpreter.SagePreparseTransformer\nFailed example:\n    shell.run_cell(bad_syntax)\nExpected:\n      File \"<string>\", line unknown\n    SyntaxError: Mismatched ']'\n    <BLANKLINE>\nGot:\n      File <string>\n    SyntaxError: Mismatched ']'\n    <BLANKLINE>\n**********************************************************************\n1 item had failures:\n   1 of  14 in sage.repl.interpreter.SagePreparseTransformer\n    [137 tests, 1 failure, 3.36 s]\nsage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interface_magic.py\n**********************************************************************\nFile \"src/sage/repl/interface_magic.py\", line 262, in sage.repl.interface_magic.InterfaceMagic.cell_magic_factory\nFailed example:\n    shell.run_cell('%%gap foo\\n1+1;\\n')\nExpected:\n    ...File \"<string>\", line unknown\n    SyntaxError: Interface magics have no options, got \"foo\"\n    <BLANKLINE>\nGot:\n    Traceback (most recent call last):\n    <BLANKLINE>\n      File /usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3251 in run_code\n        exec(code_obj, self.user_global_ns, self.user_ns)\n    <BLANKLINE>\n      Input In [1] in <module>\n        get_ipython().run_cell_magic('gap', 'foo', '1+1;\\n')\n    <BLANKLINE>\n      File /usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2257 in run_cell_magic\n        result = fn(*args, **kwargs)\n    <BLANKLINE>\n      File /usr/lib/python3.10/site-packages/sage/repl/interface_magic.py:295 in cell_magic\n        raise SyntaxError('Interface magics have no options, got \"{0}\"'.format(line))\n    <BLANKLINE>\n      File <string>\n    SyntaxError: Interface magics have no options, got \"foo\"\n    <BLANKLINE>\n**********************************************************************\n1 item had failures:\n   1 of  11 in sage.repl.interface_magic.InterfaceMagic.cell_magic_factory\n    [30 tests, 1 failure, 1.56 s]\n----------------------------------------------------------------------\nsage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interpreter.py  # 1 doctest failed\nsage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interface_magic.py  # 1 doctest failed\n----------------------------------------------------------------------\nTotal time for all tests: 15.6 seconds\n    cpu time: 3.0 seconds\n    cumulative wall time: 4.9 seconds\nFeatures detected for doctesting: \n```\n\nThe following patch fixes these:\n\n```\ndiff --git a/src/sage/repl/interface_magic.py b/src/sage/repl/interface_magic.py\nindex 8a455b69b0e..95d89628992 100644\n--- a/src/sage/repl/interface_magic.py\n+++ b/src/sage/repl/interface_magic.py\n@@ -260,7 +260,7 @@ class InterfaceMagic(object):\n             2\n             120\n             sage: shell.run_cell('%%gap foo\\n1+1;\\n')\n-            ...File \"<string>\", line unknown\n+            ...File ...<string>...\n             SyntaxError: Interface magics have no options, got \"foo\"\n             <BLANKLINE>\n             sage: shell.run_cell('%%gap?')\ndiff --git a/src/sage/repl/interpreter.py b/src/sage/repl/interpreter.py\nindex cabb71097bc..47adea3979e 100644\n--- a/src/sage/repl/interpreter.py\n+++ b/src/sage/repl/interpreter.py\n@@ -423,7 +423,7 @@ def SagePreparseTransformer(lines):\n         sage: from sage.repl.interpreter import get_test_shell\n         sage: shell = get_test_shell()\n         sage: shell.run_cell(bad_syntax)\n-          File \"<string>\", line unknown\n+          File ...<string>...\n         SyntaxError: Mismatched ']'\n         <BLANKLINE>\n         sage: shell.quit()\n```",
    "created_at": "2022-02-28T18:20:05Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536138",
    "user": "https://github.com/tornaria"
}
```

<div id="comment:10" align="right">comment:10</div>

In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:

```
$ sage -t src/sage/repl/interpreter.py src/sage/repl/interface_magic.py 
Running doctests with ID 2022-02-28-15-14-42-bbd14288.
Using --optional=build,pip,sage,sage_spkg,void
Features to be detected: 4ti2,benzene,bliss,buckygen,conway_polynomials,csdp,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_jones_numfield,database_knotinfo,dvipng,graphviz,imagemagick,jupymake,kenzo,latte_int,lrslib,mcqd,meataxe,pandoc,pdf2svg,plantri,pynormaliz,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.plot,sage.rings.number_field,sage.rings.real_double,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,sphinx,tdlib
Doctesting 2 files.
sage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interpreter.py
**********************************************************************
File "src/sage/repl/interpreter.py", line 425, in sage.repl.interpreter.SagePreparseTransformer
Failed example:
    shell.run_cell(bad_syntax)
Expected:
      File "<string>", line unknown
    SyntaxError: Mismatched ']'
    <BLANKLINE>
Got:
      File <string>
    SyntaxError: Mismatched ']'
    <BLANKLINE>
**********************************************************************
1 item had failures:
   1 of  14 in sage.repl.interpreter.SagePreparseTransformer
    [137 tests, 1 failure, 3.36 s]
sage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interface_magic.py
**********************************************************************
File "src/sage/repl/interface_magic.py", line 262, in sage.repl.interface_magic.InterfaceMagic.cell_magic_factory
Failed example:
    shell.run_cell('%%gap foo\n1+1;\n')
Expected:
    ...File "<string>", line unknown
    SyntaxError: Interface magics have no options, got "foo"
    <BLANKLINE>
Got:
    Traceback (most recent call last):
    <BLANKLINE>
      File /usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3251 in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
    <BLANKLINE>
      Input In [1] in <module>
        get_ipython().run_cell_magic('gap', 'foo', '1+1;\n')
    <BLANKLINE>
      File /usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2257 in run_cell_magic
        result = fn(*args, **kwargs)
    <BLANKLINE>
      File /usr/lib/python3.10/site-packages/sage/repl/interface_magic.py:295 in cell_magic
        raise SyntaxError('Interface magics have no options, got "{0}"'.format(line))
    <BLANKLINE>
      File <string>
    SyntaxError: Interface magics have no options, got "foo"
    <BLANKLINE>
**********************************************************************
1 item had failures:
   1 of  11 in sage.repl.interface_magic.InterfaceMagic.cell_magic_factory
    [30 tests, 1 failure, 1.56 s]
----------------------------------------------------------------------
sage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interpreter.py  # 1 doctest failed
sage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interface_magic.py  # 1 doctest failed
----------------------------------------------------------------------
Total time for all tests: 15.6 seconds
    cpu time: 3.0 seconds
    cumulative wall time: 4.9 seconds
Features detected for doctesting: 
```

The following patch fixes these:

```
diff --git a/src/sage/repl/interface_magic.py b/src/sage/repl/interface_magic.py
index 8a455b69b0e..95d89628992 100644
--- a/src/sage/repl/interface_magic.py
+++ b/src/sage/repl/interface_magic.py
@@ -260,7 +260,7 @@ class InterfaceMagic(object):
             2
             120
             sage: shell.run_cell('%%gap foo\n1+1;\n')
-            ...File "<string>", line unknown
+            ...File ...<string>...
             SyntaxError: Interface magics have no options, got "foo"
             <BLANKLINE>
             sage: shell.run_cell('%%gap?')
diff --git a/src/sage/repl/interpreter.py b/src/sage/repl/interpreter.py
index cabb71097bc..47adea3979e 100644
--- a/src/sage/repl/interpreter.py
+++ b/src/sage/repl/interpreter.py
@@ -423,7 +423,7 @@ def SagePreparseTransformer(lines):
         sage: from sage.repl.interpreter import get_test_shell
         sage: shell = get_test_shell()
         sage: shell.run_cell(bad_syntax)
-          File "<string>", line unknown
+          File ...<string>...
         SyntaxError: Mismatched ']'
         <BLANKLINE>
         sage: shell.quit()
```



---

archive/issue_comments_536139.json:
```json
{
    "body": "<div id=\"comment:11\" align=\"right\">comment:11</div>\n\nReplying to [@tornaria](#comment:10):\n> In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:\n\nThis is fixed in the branch already",
    "created_at": "2022-02-28T18:30:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536139",
    "user": "https://github.com/antonio-rojas"
}
```

<div id="comment:11" align="right">comment:11</div>

Replying to [@tornaria](#comment:10):
> In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:

This is fixed in the branch already



---

archive/issue_comments_536140.json:
```json
{
    "body": "<div id=\"comment:12\" align=\"right\">comment:12</div>\n\nReplying to [@antonio-rojas](#comment:11):\n> Replying to [@tornaria](#comment:10):\n> > In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:\n\n> \n> This is fixed in the branch already\n\nMy bad, it's there indeed as c373551, thanks.\n\nSorry for the noise.",
    "created_at": "2022-02-28T18:57:11Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536140",
    "user": "https://github.com/tornaria"
}
```

<div id="comment:12" align="right">comment:12</div>

Replying to [@antonio-rojas](#comment:11):
> Replying to [@tornaria](#comment:10):
> > In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:

> 
> This is fixed in the branch already

My bad, it's there indeed as c373551, thanks.

Sorry for the noise.



---

archive/issue_events_458628.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-04T23:25:28Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "milestone_number": null,
    "milestone_title": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458628"
}
```



---

archive/issue_events_458629.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-04T23:25:28Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "milestone_number": null,
    "milestone_title": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458629"
}
```



---

archive/issue_comments_536141.json:
```json
{
    "body": "<div id=\"comment:14\" align=\"right\">comment:14</div>\n\nThis works ok with ipython 8.0.1, but it's already broken on ipython 8.1.0 and 8.1.1:\n\n```\nFailed example:\n    print(\"dummy line\"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test\nExpected:\n    dummy line\n    ...\n    ZeroDivisionError...Traceback (most recent call last)\n    ...in <module>...\n    ----> 1 Integer(1)/Integer(0)\n    .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...\n    ...\n    -> ...                  raise ZeroDivisionError(\"rational division by zero\")\n       ...            x = <Rational> Rational.__new__(Rational)\n       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)\n    <BLANKLINE>\n    ZeroDivisionError: rational division by zero\nGot:\n    dummy line\n    ---------------------------------------------------------------------------\n    ZeroDivisionError                         Traceback (most recent call last)\n    Input In [1], in <cell line: 1>()\n    ----> 1 Integer(1)/Integer(0)\n    <BLANKLINE>\n    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13693)()\n       1985 if type(left) is type(right):\n       1986     if mpz_sgn((<Integer>right).value) == 0:\n    -> 1987         raise ZeroDivisionError(\"rational division by zero\")\n       1988     x = <Rational> Rational.__new__(Rational)\n       1989     mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)\n    <BLANKLINE>\n    ZeroDivisionError: rational division by zero\n**********************************************************************\n```\n\nCan you add the following patch on top of your previous commits?\n\n```\n--- a/src/sage/repl/interpreter.py\n+++ b/src/sage/repl/interpreter.py\n@@ -78,7 +78,7 @@ Check that Cython source code appears in tracebacks::\n     dummy line\n     ...\n     ZeroDivisionError...Traceback (most recent call last)\n-    ...in <module>...\n+    ...\n     ----> 1 Integer(1)/Integer(0)\n     .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...\n     ...\n```\nThe other file (interface_magic.py) is still ok with ipython 8.1.",
    "created_at": "2022-03-18T21:02:22Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536141",
    "user": "https://github.com/tornaria"
}
```

<div id="comment:14" align="right">comment:14</div>

This works ok with ipython 8.0.1, but it's already broken on ipython 8.1.0 and 8.1.1:

```
Failed example:
    print("dummy line"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test
Expected:
    dummy line
    ...
    ZeroDivisionError...Traceback (most recent call last)
    ...in <module>...
    ----> 1 Integer(1)/Integer(0)
    .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...
    ...
    -> ...                  raise ZeroDivisionError("rational division by zero")
       ...            x = <Rational> Rational.__new__(Rational)
       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
Got:
    dummy line
    ---------------------------------------------------------------------------
    ZeroDivisionError                         Traceback (most recent call last)
    Input In [1], in <cell line: 1>()
    ----> 1 Integer(1)/Integer(0)
    <BLANKLINE>
    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13693)()
       1985 if type(left) is type(right):
       1986     if mpz_sgn((<Integer>right).value) == 0:
    -> 1987         raise ZeroDivisionError("rational division by zero")
       1988     x = <Rational> Rational.__new__(Rational)
       1989     mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
**********************************************************************
```

Can you add the following patch on top of your previous commits?

```
--- a/src/sage/repl/interpreter.py
+++ b/src/sage/repl/interpreter.py
@@ -78,7 +78,7 @@ Check that Cython source code appears in tracebacks::
     dummy line
     ...
     ZeroDivisionError...Traceback (most recent call last)
-    ...in <module>...
+    ...
     ----> 1 Integer(1)/Integer(0)
     .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...
     ...
```
The other file (interface_magic.py) is still ok with ipython 8.1.



---

archive/issue_events_458630.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-18T21:05:03Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "milestone_number": null,
    "milestone_title": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458630"
}
```



---

archive/issue_events_458631.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-18T21:05:03Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "milestone_number": null,
    "milestone_title": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458631"
}
```



---

archive/issue_events_458632.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-18T21:05:03Z",
    "event": "renamed",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "title_is": "Update doctests for compatibility with ipython 8.x",
    "title_was": "Update to ipython 8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458632"
}
```



---

archive/issue_comments_536142.json:
```json
{
    "body": "Changed commit from **[`a90a314`](https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231)** to **[`4d2b53f`](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)**",
    "created_at": "2022-03-18T21:22:22Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536142",
    "user": "https://github.com/sagetrac-git"
}
```

Changed commit from **[`a90a314`](https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231)** to **[`4d2b53f`](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)**



---

archive/issue_comments_536143.json:
```json
{
    "body": "<div id=\"comment:16\"></div>\n\nBranch pushed to git repo; I updated commit sha1. New commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d\"><code>4d2b53f</code></a></td><td><code>Update test for ipython 8.1</code></td></tr></table>\n",
    "created_at": "2022-03-18T21:22:22Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536143",
    "user": "https://github.com/sagetrac-git"
}
```

<div id="comment:16"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d"><code>4d2b53f</code></a></td><td><code>Update test for ipython 8.1</code></td></tr></table>




---

archive/issue_comments_536144.json:
```json
{
    "body": "<div id=\"comment:17\" align=\"right\">comment:17</div>\n\nDone, thanks. Needs review since this is now only about fixing tests.",
    "created_at": "2022-03-18T21:23:46Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536144",
    "user": "https://github.com/antonio-rojas"
}
```

<div id="comment:17" align="right">comment:17</div>

Done, thanks. Needs review since this is now only about fixing tests.



---

archive/issue_events_458633.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-03-18T21:23:46Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458633"
}
```



---

archive/issue_comments_536145.json:
```json
{
    "body": "Author: **Antonio Rojas**",
    "created_at": "2022-03-18T21:26:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536145",
    "user": "https://github.com/mkoeppe"
}
```

Author: **Antonio Rojas**



---

archive/issue_comments_536146.json:
```json
{
    "body": "<div id=\"comment:19\" align=\"right\">comment:19</div>\n\nThanks, I'll give positive review once CI on https://github.com/void-linux/void-packages/pull/36209 is done.",
    "created_at": "2022-03-18T22:07:18Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536146",
    "user": "https://github.com/tornaria"
}
```

<div id="comment:19" align="right">comment:19</div>

Thanks, I'll give positive review once CI on https://github.com/void-linux/void-packages/pull/36209 is done.



---

archive/issue_events_458634.json:
```json
{
    "actor": "https://github.com/tornaria",
    "created_at": "2022-03-19T00:33:14Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458634"
}
```



---

archive/issue_events_458635.json:
```json
{
    "actor": "https://github.com/tornaria",
    "created_at": "2022-03-19T00:33:14Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458635"
}
```



---

archive/issue_comments_536147.json:
```json
{
    "body": "<div id=\"comment:20\" align=\"right\">comment:20</div>\n\nAll ok on void linux using system ipython 8.1 (glibc 64 and 32 bit, musl 64 bit tested at https://github.com/void-linux/void-packages/pull/36209)",
    "created_at": "2022-03-19T00:33:14Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536147",
    "user": "https://github.com/tornaria"
}
```

<div id="comment:20" align="right">comment:20</div>

All ok on void linux using system ipython 8.1 (glibc 64 and 32 bit, musl 64 bit tested at https://github.com/void-linux/void-packages/pull/36209)



---

archive/issue_comments_536148.json:
```json
{
    "body": "Reviewer: **Gonzalo Tornar\u00eda**",
    "created_at": "2022-03-19T00:33:14Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536148",
    "user": "https://github.com/tornaria"
}
```

Reviewer: **Gonzalo Tornar√≠a**



---

archive/issue_comments_536149.json:
```json
{
    "body": "<div id=\"comment:21\" align=\"right\">comment:21</div>\n\nReplying to [@collares](#comment:6):\n> I also asked for a clarification with regards to IPython 8's stability and, [according to the developer](https://github.com/ipython/ipython/pull/13461#issuecomment-1035560431), IPython 8 is a stable release; the notice in the release notes about it being alpha/beta quality just wasn't removed soon enough.\n\nI've opened #33530 for the actual update. This is for Sage 9.7 because the update will require us to drop support for Python 3.7.",
    "created_at": "2022-03-19T01:23:53Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536149",
    "user": "https://github.com/mkoeppe"
}
```

<div id="comment:21" align="right">comment:21</div>

Replying to [@collares](#comment:6):
> I also asked for a clarification with regards to IPython 8's stability and, [according to the developer](https://github.com/ipython/ipython/pull/13461#issuecomment-1035560431), IPython 8 is a stable release; the notice in the release notes about it being alpha/beta quality just wasn't removed soon enough.

I've opened #33530 for the actual update. This is for Sage 9.7 because the update will require us to drop support for Python 3.7.



---

archive/issue_comments_536150.json:
```json
{
    "body": "Changed branch from **[u/arojas/update_to_ipython_8](https://github.com/sagemath/sagetrac-mirror/tree/u/arojas/update_to_ipython_8)** to **[`4d2b53f`](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)**",
    "created_at": "2022-03-21T23:34:36Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33170#issuecomment-536150",
    "user": "https://github.com/vbraun"
}
```

Changed branch from **[u/arojas/update_to_ipython_8](https://github.com/sagemath/sagetrac-mirror/tree/u/arojas/update_to_ipython_8)** to **[`4d2b53f`](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)**



---

archive/issue_events_458636.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2022-03-21T23:34:36Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458636"
}
```



---

archive/issue_events_458637.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "f06a7f845e74d347892fadb77d661abe634ecb16",
    "commit_repository": "https://github.com/sagemath/sage",
    "created_at": "2022-03-21T23:34:36Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/33170",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33170#event-458637"
}
```
