# Issue 33170: Update doctests for compatibility with ipython 8.x

archive/issues_032933.json:
```json
{
    "body": "Besides trivial output format changes, the only breakage seems to be tracebacks no longer showing cython source code\n\n```\n**********************************************************************\nFile \"src/sage/repl/interpreter.py\", line 77, in sage.repl.interpreter\nFailed example:\n    print(\"dummy line\"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test\nExpected:\n    dummy line\n    ...\n    ZeroDivisionError...Traceback (most recent call last)\n    <ipython-input-...> in <module>...\n    ----> 1 Integer(1)/Integer(0)\n    .../sage/rings/integer.pyx in sage.rings.integer.Integer...div...\n    ...\n    -> ...                  raise ZeroDivisionError(\"rational division by zero\")\n       ...            x = <Rational> Rational.__new__(Rational)\n       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)\n    <BLANKLINE>\n    ZeroDivisionError: rational division by zero\nGot:\n    dummy line\n    ---------------------------------------------------------------------------\n    ZeroDivisionError                         Traceback (most recent call last)\n    Input In [1], in <module>\n    ----> 1 Integer(1)/Integer(0)\n    <BLANKLINE>\n    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13679)()\n    <BLANKLINE>\n    ZeroDivisionError: rational division by zero\n**********************************************************************\n```\nThe update itself requires a bunch of new dependencies\n\n**CC:**  @mkoeppe @kiwifb @collares\n\n**Branch/Commit:** [4d2b53f1541375861310af3a7f7109c1c2ed475d](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)\n\n**Reviewer:** Gonzalo Tornar\u00eda\n\n**Author:** Antonio Rojas\n\nIssue created by migration from https://trac.sagemath.org/ticket/33170\n\n",
    "closed_at": "2022-03-21T23:34:36Z",
    "created_at": "2022-01-14T19:53:07Z",
    "labels": [
        "component: packages: standard",
        "enhancement"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-9.6",
    "title": "Update doctests for compatibility with ipython 8.x",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/33170",
    "user": "https://github.com/antonio-rojas"
}
```
Besides trivial output format changes, the only breakage seems to be tracebacks no longer showing cython source code

```
**********************************************************************
File "src/sage/repl/interpreter.py", line 77, in sage.repl.interpreter
Failed example:
    print("dummy line"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test
Expected:
    dummy line
    ...
    ZeroDivisionError...Traceback (most recent call last)
    <ipython-input-...> in <module>...
    ----> 1 Integer(1)/Integer(0)
    .../sage/rings/integer.pyx in sage.rings.integer.Integer...div...
    ...
    -> ...                  raise ZeroDivisionError("rational division by zero")
       ...            x = <Rational> Rational.__new__(Rational)
       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
Got:
    dummy line
    ---------------------------------------------------------------------------
    ZeroDivisionError                         Traceback (most recent call last)
    Input In [1], in <module>
    ----> 1 Integer(1)/Integer(0)
    <BLANKLINE>
    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13679)()
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
**********************************************************************
```
The update itself requires a bunch of new dependencies

**CC:**  @mkoeppe @kiwifb @collares

**Branch/Commit:** [4d2b53f1541375861310af3a7f7109c1c2ed475d](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)

**Reviewer:** Gonzalo Tornar√≠a

**Author:** Antonio Rojas

Issue created by migration from https://trac.sagemath.org/ticket/33170





---

archive/issue_comments_632594.json:
```json
{
    "body": "**Branch:** [u/arojas/update_to_ipython_8](https://github.com/sagemath/sagetrac-mirror/tree/u/arojas/update_to_ipython_8)",
    "created_at": "2022-01-14T19:54:09Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632594",
    "user": "https://github.com/antonio-rojas"
}
```

**Branch:** [u/arojas/update_to_ipython_8](https://github.com/sagemath/sagetrac-mirror/tree/u/arojas/update_to_ipython_8)



---

archive/issue_comments_632595.json:
```json
{
    "body": "**Commit:** [c3735515576a6d8949acf160b7072e347026ae70](https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70)",
    "created_at": "2022-01-14T19:57:54Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632595",
    "user": "https://github.com/antonio-rojas"
}
```

**Commit:** [c3735515576a6d8949acf160b7072e347026ae70](https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70)



---

archive/issue_events_098291.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-01-14T19:57:54Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "milestone": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/33170#event-98291"
}
```



---

archive/issue_comments_632596.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1 +1,33 @@\n+Besides trivial output format changes, the only breakage seems to be tracebacks no longer showing cython source code\n \n+```\n+**********************************************************************\n+File \"src/sage/repl/interpreter.py\", line 77, in sage.repl.interpreter\n+Failed example:\n+    print(\"dummy line\"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test\n+Expected:\n+    dummy line\n+    ...\n+    ZeroDivisionError...Traceback (most recent call last)\n+    <ipython-input-...> in <module>...\n+    ----> 1 Integer(1)/Integer(0)\n+    .../sage/rings/integer.pyx in sage.rings.integer.Integer...div...\n+    ...\n+    -> ...                  raise ZeroDivisionError(\"rational division by zero\")\n+       ...            x = <Rational> Rational.__new__(Rational)\n+       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)\n+    <BLANKLINE>\n+    ZeroDivisionError: rational division by zero\n+Got:\n+    dummy line\n+    ---------------------------------------------------------------------------\n+    ZeroDivisionError                         Traceback (most recent call last)\n+    Input In [1], in <module>\n+    ----> 1 Integer(1)/Integer(0)\n+    <BLANKLINE>\n+    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13679)()\n+    <BLANKLINE>\n+    ZeroDivisionError: rational division by zero\n+**********************************************************************\n+```\n+The update itself requires a bunch of new dependencies\n``````\n",
    "created_at": "2022-01-14T19:57:54Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632596",
    "user": "https://github.com/antonio-rojas"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1 +1,33 @@
+Besides trivial output format changes, the only breakage seems to be tracebacks no longer showing cython source code
 
+```
+**********************************************************************
+File "src/sage/repl/interpreter.py", line 77, in sage.repl.interpreter
+Failed example:
+    print("dummy line"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test
+Expected:
+    dummy line
+    ...
+    ZeroDivisionError...Traceback (most recent call last)
+    <ipython-input-...> in <module>...
+    ----> 1 Integer(1)/Integer(0)
+    .../sage/rings/integer.pyx in sage.rings.integer.Integer...div...
+    ...
+    -> ...                  raise ZeroDivisionError("rational division by zero")
+       ...            x = <Rational> Rational.__new__(Rational)
+       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)
+    <BLANKLINE>
+    ZeroDivisionError: rational division by zero
+Got:
+    dummy line
+    ---------------------------------------------------------------------------
+    ZeroDivisionError                         Traceback (most recent call last)
+    Input In [1], in <module>
+    ----> 1 Integer(1)/Integer(0)
+    <BLANKLINE>
+    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13679)()
+    <BLANKLINE>
+    ZeroDivisionError: rational division by zero
+**********************************************************************
+```
+The update itself requires a bunch of new dependencies
``````




---

archive/issue_comments_632597.json:
```json
{
    "body": "<a id='comment:2'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70\">c373551</a></td><td><code>Fix tests expected output to match ipython 8</code></td></tr></table>\n",
    "created_at": "2022-01-14T19:57:54Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632597",
    "user": "https://github.com/antonio-rojas"
}
```

<a id='comment:2'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70">c373551</a></td><td><code>Fix tests expected output to match ipython 8</code></td></tr></table>




---

archive/issue_comments_632598.json:
```json
{
    "body": "<a id='comment:3'></a>\n(Thank you for maintaining Sage on archlinux! Just updated to 9.5)\n\nI think it might be a good idea to document somewhere how to disable the autoformatter and suggestion in IPython 8, which are enabled by default (also useful for people who haven't updated to IPython 8 and want to enable these features)\n\n```\nshell = get_ipython()\nshell.autoformatter = None\nshell.pt_app.auto_suggest = None\n# from prompt_toolkit.auto_suggest import AutoSuggestFromHistory\n# shell.autoformatter = \"black\"\n# shell.pt_app.auto_suggest = AutoSuggestFromHistory()\n```",
    "created_at": "2022-01-30T22:02:28Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632598",
    "user": "https://github.com/8d1h"
}
```

<a id='comment:3'></a>
(Thank you for maintaining Sage on archlinux! Just updated to 9.5)

I think it might be a good idea to document somewhere how to disable the autoformatter and suggestion in IPython 8, which are enabled by default (also useful for people who haven't updated to IPython 8 and want to enable these features)

```
shell = get_ipython()
shell.autoformatter = None
shell.pt_app.auto_suggest = None
# from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
# shell.autoformatter = "black"
# shell.pt_app.auto_suggest = AutoSuggestFromHistory()
```



---

archive/issue_comments_632599.json:
```json
{
    "body": "<a id='comment:4'></a>\nAccording to release notes, IPython 8 is still in alpha/beta stage,  https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-0\n\nSo I don't think we should do the actual update soon. Perhaps open a separate ticket for the update and only put doctest adjustments on the present ticket?",
    "created_at": "2022-01-30T22:09:51Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632599",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:4'></a>
According to release notes, IPython 8 is still in alpha/beta stage,  https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-0

So I don't think we should do the actual update soon. Perhaps open a separate ticket for the update and only put doctest adjustments on the present ticket?



---

archive/issue_comments_632600.json:
```json
{
    "body": "<a id='comment:5'></a>\nReplying to [gh-8d1h](#comment%3A3):\n> I think it might be a good idea to document somewhere how to disable the autoformatter and suggestion in IPython 8, which are enabled by default\n\n\nIn my opinion, we should actually disable these features by default. They change Sage's behavior in a potentially very irritating way and many users won't even know what is causing it and which keywords to search for to change it back.",
    "created_at": "2022-02-01T07:14:48Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632600",
    "user": "https://github.com/yyyyx4"
}
```

<a id='comment:5'></a>
Replying to [gh-8d1h](#comment%3A3):
> I think it might be a good idea to document somewhere how to disable the autoformatter and suggestion in IPython 8, which are enabled by default


In my opinion, we should actually disable these features by default. They change Sage's behavior in a potentially very irritating way and many users won't even know what is causing it and which keywords to search for to change it back.



---

archive/issue_comments_632601.json:
```json
{
    "body": "<a id='comment:6'></a>\nI filed https://github.com/alexmojaki/stack_data/issues/21 to address the lack of Cython source code in tracebacks. I also asked for a clarification with regards to IPython 8's stability and, [according to the developer](https://github.com/ipython/ipython/pull/13461#issuecomment-1035560431), IPython 8 is a stable release; the notice in the release notes about it being alpha/beta quality just wasn't removed soon enough.",
    "created_at": "2022-02-11T21:45:36Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632601",
    "user": "https://github.com/collares"
}
```

<a id='comment:6'></a>
I filed https://github.com/alexmojaki/stack_data/issues/21 to address the lack of Cython source code in tracebacks. I also asked for a clarification with regards to IPython 8's stability and, [according to the developer](https://github.com/ipython/ipython/pull/13461#issuecomment-1035560431), IPython 8 is a stable release; the notice in the release notes about it being alpha/beta quality just wasn't removed soon enough.



---

archive/issue_comments_632602.json:
```json
{
    "body": "<a id='comment:7'></a>\nAlthough I won't have time to test it until next week, upstream just reported that Cython source code should now appear on tracebacks if Python package `stack_data` is updated to 0.2.0.",
    "created_at": "2022-02-14T19:01:28Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632602",
    "user": "https://github.com/collares"
}
```

<a id='comment:7'></a>
Although I won't have time to test it until next week, upstream just reported that Cython source code should now appear on tracebacks if Python package `stack_data` is updated to 0.2.0.



---

archive/issue_comments_632603.json:
```json
{
    "body": "<a id='comment:8'></a>\n**Branch pushed to git repo; I updated commit sha1.** **New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231\">a90a314</a></td><td><code>Fix cython source test output for ipython 8 syntax</code></td></tr></table>\n",
    "created_at": "2022-02-14T19:21:22Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632603",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

<a id='comment:8'></a>
**Branch pushed to git repo; I updated commit sha1.** **New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231">a90a314</a></td><td><code>Fix cython source test output for ipython 8 syntax</code></td></tr></table>




---

archive/issue_comments_632604.json:
```json
{
    "body": "**Changing commit** from \"[c3735515576a6d8949acf160b7072e347026ae70](https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70)\" to \"[a90a314616d86d6be9c0d5233f0d36c4bfe06231](https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231)\".",
    "created_at": "2022-02-14T19:21:22Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632604",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

**Changing commit** from "[c3735515576a6d8949acf160b7072e347026ae70](https://github.com/sagemath/sagetrac-mirror/commit/c3735515576a6d8949acf160b7072e347026ae70)" to "[a90a314616d86d6be9c0d5233f0d36c4bfe06231](https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231)".



---

archive/issue_comments_632605.json:
```json
{
    "body": "<a id='comment:9'></a>\nReplying to [gh-collares](#comment%3A7):\n> Although I won't have time to test it until next week, upstream just reported that Cython source code should now appear on tracebacks if Python package `stack_data` is updated to 0.2.0.\n\n\nConfirmed, thanks. Test still failed because of slightly different syntax, should be fixed now.",
    "created_at": "2022-02-14T19:22:42Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632605",
    "user": "https://github.com/antonio-rojas"
}
```

<a id='comment:9'></a>
Replying to [gh-collares](#comment%3A7):
> Although I won't have time to test it until next week, upstream just reported that Cython source code should now appear on tracebacks if Python package `stack_data` is updated to 0.2.0.


Confirmed, thanks. Test still failed because of slightly different syntax, should be fixed now.



---

archive/issue_comments_632606.json:
```json
{
    "body": "<a id='comment:10'></a>\nIn addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:\n\n```\n$ sage -t src/sage/repl/interpreter.py src/sage/repl/interface_magic.py \nRunning doctests with ID 2022-02-28-15-14-42-bbd14288.\nUsing --optional=build,pip,sage,sage_spkg,void\nFeatures to be detected: 4ti2,benzene,bliss,buckygen,conway_polynomials,csdp,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_jones_numfield,database_knotinfo,dvipng,graphviz,imagemagick,jupymake,kenzo,latte_int,lrslib,mcqd,meataxe,pandoc,pdf2svg,plantri,pynormaliz,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.plot,sage.rings.number_field,sage.rings.real_double,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,sphinx,tdlib\nDoctesting 2 files.\nsage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interpreter.py\n**********************************************************************\nFile \"src/sage/repl/interpreter.py\", line 425, in sage.repl.interpreter.SagePreparseTransformer\nFailed example:\n    shell.run_cell(bad_syntax)\nExpected:\n      File \"<string>\", line unknown\n    SyntaxError: Mismatched ']'\n    <BLANKLINE>\nGot:\n      File <string>\n    SyntaxError: Mismatched ']'\n    <BLANKLINE>\n**********************************************************************\n1 item had failures:\n   1 of  14 in sage.repl.interpreter.SagePreparseTransformer\n    [137 tests, 1 failure, 3.36 s]\nsage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interface_magic.py\n**********************************************************************\nFile \"src/sage/repl/interface_magic.py\", line 262, in sage.repl.interface_magic.InterfaceMagic.cell_magic_factory\nFailed example:\n    shell.run_cell('%%gap foo\\n1+1;\\n')\nExpected:\n    ...File \"<string>\", line unknown\n    SyntaxError: Interface magics have no options, got \"foo\"\n    <BLANKLINE>\nGot:\n    Traceback (most recent call last):\n    <BLANKLINE>\n      File /usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3251 in run_code\n        exec(code_obj, self.user_global_ns, self.user_ns)\n    <BLANKLINE>\n      Input In [1] in <module>\n        get_ipython().run_cell_magic('gap', 'foo', '1+1;\\n')\n    <BLANKLINE>\n      File /usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2257 in run_cell_magic\n        result = fn(*args, **kwargs)\n    <BLANKLINE>\n      File /usr/lib/python3.10/site-packages/sage/repl/interface_magic.py:295 in cell_magic\n        raise SyntaxError('Interface magics have no options, got \"{0}\"'.format(line))\n    <BLANKLINE>\n      File <string>\n    SyntaxError: Interface magics have no options, got \"foo\"\n    <BLANKLINE>\n**********************************************************************\n1 item had failures:\n   1 of  11 in sage.repl.interface_magic.InterfaceMagic.cell_magic_factory\n    [30 tests, 1 failure, 1.56 s]\n----------------------------------------------------------------------\nsage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interpreter.py  # 1 doctest failed\nsage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interface_magic.py  # 1 doctest failed\n----------------------------------------------------------------------\nTotal time for all tests: 15.6 seconds\n    cpu time: 3.0 seconds\n    cumulative wall time: 4.9 seconds\nFeatures detected for doctesting: \n```\n\nThe following patch fixes these:\n\n```\ndiff --git a/src/sage/repl/interface_magic.py b/src/sage/repl/interface_magic.py\nindex 8a455b69b0e..95d89628992 100644\n--- a/src/sage/repl/interface_magic.py\n+++ b/src/sage/repl/interface_magic.py\n@@ -260,7 +260,7 @@ class InterfaceMagic(object):\n             2\n             120\n             sage: shell.run_cell('%%gap foo\\n1+1;\\n')\n-            ...File \"<string>\", line unknown\n+            ...File ...<string>...\n             SyntaxError: Interface magics have no options, got \"foo\"\n             <BLANKLINE>\n             sage: shell.run_cell('%%gap?')\ndiff --git a/src/sage/repl/interpreter.py b/src/sage/repl/interpreter.py\nindex cabb71097bc..47adea3979e 100644\n--- a/src/sage/repl/interpreter.py\n+++ b/src/sage/repl/interpreter.py\n@@ -423,7 +423,7 @@ def SagePreparseTransformer(lines):\n         sage: from sage.repl.interpreter import get_test_shell\n         sage: shell = get_test_shell()\n         sage: shell.run_cell(bad_syntax)\n-          File \"<string>\", line unknown\n+          File ...<string>...\n         SyntaxError: Mismatched ']'\n         <BLANKLINE>\n         sage: shell.quit()\n```",
    "created_at": "2022-02-28T18:20:05Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632606",
    "user": "https://github.com/tornaria"
}
```

<a id='comment:10'></a>
In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:

```
$ sage -t src/sage/repl/interpreter.py src/sage/repl/interface_magic.py 
Running doctests with ID 2022-02-28-15-14-42-bbd14288.
Using --optional=build,pip,sage,sage_spkg,void
Features to be detected: 4ti2,benzene,bliss,buckygen,conway_polynomials,csdp,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_jones_numfield,database_knotinfo,dvipng,graphviz,imagemagick,jupymake,kenzo,latte_int,lrslib,mcqd,meataxe,pandoc,pdf2svg,plantri,pynormaliz,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.plot,sage.rings.number_field,sage.rings.real_double,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,sphinx,tdlib
Doctesting 2 files.
sage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interpreter.py
**********************************************************************
File "src/sage/repl/interpreter.py", line 425, in sage.repl.interpreter.SagePreparseTransformer
Failed example:
    shell.run_cell(bad_syntax)
Expected:
      File "<string>", line unknown
    SyntaxError: Mismatched ']'
    <BLANKLINE>
Got:
      File <string>
    SyntaxError: Mismatched ']'
    <BLANKLINE>
**********************************************************************
1 item had failures:
   1 of  14 in sage.repl.interpreter.SagePreparseTransformer
    [137 tests, 1 failure, 3.36 s]
sage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interface_magic.py
**********************************************************************
File "src/sage/repl/interface_magic.py", line 262, in sage.repl.interface_magic.InterfaceMagic.cell_magic_factory
Failed example:
    shell.run_cell('%%gap foo\n1+1;\n')
Expected:
    ...File "<string>", line unknown
    SyntaxError: Interface magics have no options, got "foo"
    <BLANKLINE>
Got:
    Traceback (most recent call last):
    <BLANKLINE>
      File /usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3251 in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
    <BLANKLINE>
      Input In [1] in <module>
        get_ipython().run_cell_magic('gap', 'foo', '1+1;\n')
    <BLANKLINE>
      File /usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2257 in run_cell_magic
        result = fn(*args, **kwargs)
    <BLANKLINE>
      File /usr/lib/python3.10/site-packages/sage/repl/interface_magic.py:295 in cell_magic
        raise SyntaxError('Interface magics have no options, got "{0}"'.format(line))
    <BLANKLINE>
      File <string>
    SyntaxError: Interface magics have no options, got "foo"
    <BLANKLINE>
**********************************************************************
1 item had failures:
   1 of  11 in sage.repl.interface_magic.InterfaceMagic.cell_magic_factory
    [30 tests, 1 failure, 1.56 s]
----------------------------------------------------------------------
sage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interpreter.py  # 1 doctest failed
sage -t --warn-long 32.0 --random-seed=265810042777151130630499733658806769461 src/sage/repl/interface_magic.py  # 1 doctest failed
----------------------------------------------------------------------
Total time for all tests: 15.6 seconds
    cpu time: 3.0 seconds
    cumulative wall time: 4.9 seconds
Features detected for doctesting: 
```

The following patch fixes these:

```
diff --git a/src/sage/repl/interface_magic.py b/src/sage/repl/interface_magic.py
index 8a455b69b0e..95d89628992 100644
--- a/src/sage/repl/interface_magic.py
+++ b/src/sage/repl/interface_magic.py
@@ -260,7 +260,7 @@ class InterfaceMagic(object):
             2
             120
             sage: shell.run_cell('%%gap foo\n1+1;\n')
-            ...File "<string>", line unknown
+            ...File ...<string>...
             SyntaxError: Interface magics have no options, got "foo"
             <BLANKLINE>
             sage: shell.run_cell('%%gap?')
diff --git a/src/sage/repl/interpreter.py b/src/sage/repl/interpreter.py
index cabb71097bc..47adea3979e 100644
--- a/src/sage/repl/interpreter.py
+++ b/src/sage/repl/interpreter.py
@@ -423,7 +423,7 @@ def SagePreparseTransformer(lines):
         sage: from sage.repl.interpreter import get_test_shell
         sage: shell = get_test_shell()
         sage: shell.run_cell(bad_syntax)
-          File "<string>", line unknown
+          File ...<string>...
         SyntaxError: Mismatched ']'
         <BLANKLINE>
         sage: shell.quit()
```



---

archive/issue_comments_632607.json:
```json
{
    "body": "<a id='comment:11'></a>\nReplying to [tornaria](#comment%3A10):\n> In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:\n\n\nThis is fixed in the branch already",
    "created_at": "2022-02-28T18:30:26Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632607",
    "user": "https://github.com/antonio-rojas"
}
```

<a id='comment:11'></a>
Replying to [tornaria](#comment%3A10):
> In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:


This is fixed in the branch already



---

archive/issue_comments_632608.json:
```json
{
    "body": "<a id='comment:12'></a>\nReplying to [arojas](#comment%3A11):\n> Replying to [tornaria](#comment%3A10):\n> > In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:\n\n> \n> This is fixed in the branch already\n\n\nMy bad, it's there indeed as c373551, thanks.\n\nSorry for the noise.",
    "created_at": "2022-02-28T18:57:11Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632608",
    "user": "https://github.com/tornaria"
}
```

<a id='comment:12'></a>
Replying to [arojas](#comment%3A11):
> Replying to [tornaria](#comment%3A10):
> > In addition to the failure reported in the description (which a90a314 fixes) I'm getting two more doctest failures when upgrading to ipython 8.0.1:

> 
> This is fixed in the branch already


My bad, it's there indeed as c373551, thanks.

Sorry for the noise.



---

archive/issue_events_098292.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-04T23:25:28Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "milestone": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/33170#event-98292"
}
```



---

archive/issue_events_098293.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-04T23:25:28Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "milestone": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/33170#event-98293"
}
```



---

archive/issue_comments_632609.json:
```json
{
    "body": "<a id='comment:14'></a>\nThis works ok with ipython 8.0.1, but it's already broken on ipython 8.1.0 and 8.1.1:\n\n```\nFailed example:\n    print(\"dummy line\"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test\nExpected:\n    dummy line\n    ...\n    ZeroDivisionError...Traceback (most recent call last)\n    ...in <module>...\n    ----> 1 Integer(1)/Integer(0)\n    .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...\n    ...\n    -> ...                  raise ZeroDivisionError(\"rational division by zero\")\n       ...            x = <Rational> Rational.__new__(Rational)\n       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)\n    <BLANKLINE>\n    ZeroDivisionError: rational division by zero\nGot:\n    dummy line\n    ---------------------------------------------------------------------------\n    ZeroDivisionError                         Traceback (most recent call last)\n    Input In [1], in <cell line: 1>()\n    ----> 1 Integer(1)/Integer(0)\n    <BLANKLINE>\n    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13693)()\n       1985 if type(left) is type(right):\n       1986     if mpz_sgn((<Integer>right).value) == 0:\n    -> 1987         raise ZeroDivisionError(\"rational division by zero\")\n       1988     x = <Rational> Rational.__new__(Rational)\n       1989     mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)\n    <BLANKLINE>\n    ZeroDivisionError: rational division by zero\n**********************************************************************\n```\n\nCan you add the following patch on top of your previous commits?\n\n```\n--- a/src/sage/repl/interpreter.py\n+++ b/src/sage/repl/interpreter.py\n@@ -78,7 +78,7 @@ Check that Cython source code appears in tracebacks::\n     dummy line\n     ...\n     ZeroDivisionError...Traceback (most recent call last)\n-    ...in <module>...\n+    ...\n     ----> 1 Integer(1)/Integer(0)\n     .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...\n     ...\n```\nThe other file (interface_magic.py) is still ok with ipython 8.1.",
    "created_at": "2022-03-18T21:02:22Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632609",
    "user": "https://github.com/tornaria"
}
```

<a id='comment:14'></a>
This works ok with ipython 8.0.1, but it's already broken on ipython 8.1.0 and 8.1.1:

```
Failed example:
    print("dummy line"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test
Expected:
    dummy line
    ...
    ZeroDivisionError...Traceback (most recent call last)
    ...in <module>...
    ----> 1 Integer(1)/Integer(0)
    .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...
    ...
    -> ...                  raise ZeroDivisionError("rational division by zero")
       ...            x = <Rational> Rational.__new__(Rational)
       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
Got:
    dummy line
    ---------------------------------------------------------------------------
    ZeroDivisionError                         Traceback (most recent call last)
    Input In [1], in <cell line: 1>()
    ----> 1 Integer(1)/Integer(0)
    <BLANKLINE>
    File /usr/lib/python3.10/site-packages/sage/rings/integer.pyx:1987, in sage.rings.integer.Integer.__truediv__ (build/cythonized/sage/rings/integer.c:13693)()
       1985 if type(left) is type(right):
       1986     if mpz_sgn((<Integer>right).value) == 0:
    -> 1987         raise ZeroDivisionError("rational division by zero")
       1988     x = <Rational> Rational.__new__(Rational)
       1989     mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
**********************************************************************
```

Can you add the following patch on top of your previous commits?

```
--- a/src/sage/repl/interpreter.py
+++ b/src/sage/repl/interpreter.py
@@ -78,7 +78,7 @@ Check that Cython source code appears in tracebacks::
     dummy line
     ...
     ZeroDivisionError...Traceback (most recent call last)
-    ...in <module>...
+    ...
     ----> 1 Integer(1)/Integer(0)
     .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...
     ...
```
The other file (interface_magic.py) is still ok with ipython 8.1.



---

archive/issue_events_098294.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-18T21:05:03Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "milestone": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/33170#event-98294"
}
```



---

archive/issue_events_098295.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-03-18T21:05:03Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "milestone": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/33170#event-98295"
}
```



---

archive/issue_events_098296.json:
```json
{
    "event": "renamed",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "rename": {
        "from": "Update to ipython 8",
        "to": "Update doctests for compatibility with ipython 8.x"
    },
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/33170#event-98296"
}
```



---

archive/issue_comments_632610.json:
```json
{
    "body": "**Changing commit** from \"[a90a314616d86d6be9c0d5233f0d36c4bfe06231](https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231)\" to \"[4d2b53f1541375861310af3a7f7109c1c2ed475d](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)\".",
    "created_at": "2022-03-18T21:22:22Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632610",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

**Changing commit** from "[a90a314616d86d6be9c0d5233f0d36c4bfe06231](https://github.com/sagemath/sagetrac-mirror/commit/a90a314616d86d6be9c0d5233f0d36c4bfe06231)" to "[4d2b53f1541375861310af3a7f7109c1c2ed475d](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)".



---

archive/issue_comments_632611.json:
```json
{
    "body": "<a id='comment:16'></a>\n**Branch pushed to git repo; I updated commit sha1.** **New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d\">4d2b53f</a></td><td><code>Update test for ipython 8.1</code></td></tr></table>\n",
    "created_at": "2022-03-18T21:22:22Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632611",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

<a id='comment:16'></a>
**Branch pushed to git repo; I updated commit sha1.** **New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d">4d2b53f</a></td><td><code>Update test for ipython 8.1</code></td></tr></table>




---

archive/issue_comments_632612.json:
```json
{
    "body": "<a id='comment:17'></a>\nDone, thanks. Needs review since this is now only about fixing tests.",
    "created_at": "2022-03-18T21:23:46Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632612",
    "user": "https://github.com/antonio-rojas"
}
```

<a id='comment:17'></a>
Done, thanks. Needs review since this is now only about fixing tests.



---

archive/issue_comments_632613.json:
```json
{
    "body": "**Changing status** from new to needs_review.",
    "created_at": "2022-03-18T21:23:46Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632613",
    "user": "https://github.com/antonio-rojas"
}
```

**Changing status** from new to needs_review.



---

archive/issue_comments_632614.json:
```json
{
    "body": "**Author:** Antonio Rojas",
    "created_at": "2022-03-18T21:26:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632614",
    "user": "https://github.com/mkoeppe"
}
```

**Author:** Antonio Rojas



---

archive/issue_comments_632615.json:
```json
{
    "body": "<a id='comment:19'></a>\nThanks, I'll give positive review once CI on https://github.com/void-linux/void-packages/pull/36209 is done.",
    "created_at": "2022-03-18T22:07:18Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632615",
    "user": "https://github.com/tornaria"
}
```

<a id='comment:19'></a>
Thanks, I'll give positive review once CI on https://github.com/void-linux/void-packages/pull/36209 is done.



---

archive/issue_comments_632616.json:
```json
{
    "body": "**Changing status** from needs_review to positive_review.",
    "created_at": "2022-03-19T00:33:14Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632616",
    "user": "https://github.com/tornaria"
}
```

**Changing status** from needs_review to positive_review.



---

archive/issue_comments_632617.json:
```json
{
    "body": "<a id='comment:20'></a>\nAll ok on void linux using system ipython 8.1 (glibc 64 and 32 bit, musl 64 bit tested at https://github.com/void-linux/void-packages/pull/36209)",
    "created_at": "2022-03-19T00:33:14Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632617",
    "user": "https://github.com/tornaria"
}
```

<a id='comment:20'></a>
All ok on void linux using system ipython 8.1 (glibc 64 and 32 bit, musl 64 bit tested at https://github.com/void-linux/void-packages/pull/36209)



---

archive/issue_comments_632618.json:
```json
{
    "body": "**Reviewer:** Gonzalo Tornar\u00eda",
    "created_at": "2022-03-19T00:33:14Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632618",
    "user": "https://github.com/tornaria"
}
```

**Reviewer:** Gonzalo Tornar√≠a



---

archive/issue_comments_632619.json:
```json
{
    "body": "<a id='comment:21'></a>\nReplying to [gh-collares](#comment%3A6):\n> I also asked for a clarification with regards to IPython 8's stability and, [according to the developer](https://github.com/ipython/ipython/pull/13461#issuecomment-1035560431), IPython 8 is a stable release; the notice in the release notes about it being alpha/beta quality just wasn't removed soon enough.\n\n\nI've opened #33530 for the actual update. This is for Sage 9.7 because the update will require us to drop support for Python 3.7.",
    "created_at": "2022-03-19T01:23:53Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632619",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:21'></a>
Replying to [gh-collares](#comment%3A6):
> I also asked for a clarification with regards to IPython 8's stability and, [according to the developer](https://github.com/ipython/ipython/pull/13461#issuecomment-1035560431), IPython 8 is a stable release; the notice in the release notes about it being alpha/beta quality just wasn't removed soon enough.


I've opened #33530 for the actual update. This is for Sage 9.7 because the update will require us to drop support for Python 3.7.



---

archive/issue_comments_632620.json:
```json
{
    "body": "**Changing branch** from \"[u/arojas/update_to_ipython_8](https://github.com/sagemath/sagetrac-mirror/tree/u/arojas/update_to_ipython_8)\" to \"[4d2b53f1541375861310af3a7f7109c1c2ed475d](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)\".",
    "created_at": "2022-03-21T23:34:36Z",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/33170#issuecomment-632620",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/arojas/update_to_ipython_8](https://github.com/sagemath/sagetrac-mirror/tree/u/arojas/update_to_ipython_8)" to "[4d2b53f1541375861310af3a7f7109c1c2ed475d](https://github.com/sagemath/sagetrac-mirror/commit/4d2b53f1541375861310af3a7f7109c1c2ed475d)".



---

archive/issue_events_098297.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2022-03-21T23:34:36Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/33170",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/33170#event-98297"
}
```
