# Issue 24698: fixing one plantri doctest

archive/issues_024461.json:
```json
{
    "body": "Future division made a doctest failure with the optional package plantri installed\n\n```\nsage -t --long src/sage/graphs/graph_generators.py\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1408, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    [u for u in list(gen)]  # optional plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>\", line 1, in <module>\n        [u for u in list(gen)]  # optional plantri\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n        for G in graphs._read_planar_code(sp.stdout):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n        edges_g[i + 1] += [i + 1] * (Ni / 2)\n    TypeError: can't multiply sequence by non-int of type 'float'\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1439, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>\", line 1, in <module>\n        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n        for G in graphs._read_planar_code(sp.stdout):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n        edges_g[i + 1] += [i + 1] * (Ni / 2)\n    TypeError: can't multiply sequence by non-int of type 'float'\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1441, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar_sizes      = [g.size() for g in planar]         # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>\", line 1, in <module>\n        planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n    NameError: name 'planar' is not defined\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1443, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar_sizes == dual_planar_sizes                      # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>\", line 1, in <module>\n        planar_sizes == dual_planar_sizes                      # optional -- plantri\n    NameError: name 'planar_sizes' is not defined\n**********************************************************************\n1 item had failures:\n   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?\n    [140 tests, 4 failures, 29.80 s]\n```\n\n**CC:**  @tscrim @embray @jdemeyer\n\n**Branch/Commit:** [a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)\n\n**Reviewer:** Travis Scrimshaw\n\n**Author:** Fr\u00e9d\u00e9ric Chapoton\n\nIssue created by migration from https://trac.sagemath.org/ticket/24698\n\n",
    "closed_at": "2018-02-16T23:39:03Z",
    "created_at": "2018-02-09T16:52:43Z",
    "labels": [
        "component: graph theory",
        "blocker",
        "enhancement"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-8.2",
    "title": "fixing one plantri doctest",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/24698",
    "user": "https://github.com/fchapoton"
}
```
Future division made a doctest failure with the optional package plantri installed

```
sage -t --long src/sage/graphs/graph_generators.py
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1408, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    [u for u in list(gen)]  # optional plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>", line 1, in <module>
        [u for u in list(gen)]  # optional plantri
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
        for G in graphs._read_planar_code(sp.stdout):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
        edges_g[i + 1] += [i + 1] * (Ni / 2)
    TypeError: can't multiply sequence by non-int of type 'float'
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1439, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>", line 1, in <module>
        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
        for G in graphs._read_planar_code(sp.stdout):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
        edges_g[i + 1] += [i + 1] * (Ni / 2)
    TypeError: can't multiply sequence by non-int of type 'float'
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1441, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar_sizes      = [g.size() for g in planar]         # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>", line 1, in <module>
        planar_sizes      = [g.size() for g in planar]         # optional -- plantri
    NameError: name 'planar' is not defined
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1443, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar_sizes == dual_planar_sizes                      # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>", line 1, in <module>
        planar_sizes == dual_planar_sizes                      # optional -- plantri
    NameError: name 'planar_sizes' is not defined
**********************************************************************
1 item had failures:
   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?
    [140 tests, 4 failures, 29.80 s]
```

**CC:**  @tscrim @embray @jdemeyer

**Branch/Commit:** [a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)

**Reviewer:** Travis Scrimshaw

**Author:** Frédéric Chapoton

Issue created by migration from https://trac.sagemath.org/ticket/24698





---

archive/issue_comments_448915.json:
```json
{
    "body": "**Branch:** [u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)",
    "created_at": "2018-02-09T16:53:26Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448915",
    "user": "https://github.com/fchapoton"
}
```

**Branch:** [u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)



---

archive/issue_comments_448916.json:
```json
{
    "body": "**Changing status** from new to needs_review.",
    "created_at": "2018-02-09T16:53:26Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448916",
    "user": "https://github.com/fchapoton"
}
```

**Changing status** from new to needs_review.



---

archive/issue_comments_448917.json:
```json
{
    "body": "<a id='comment:1'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc\">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>\n",
    "created_at": "2018-02-09T16:53:26Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448917",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:1'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>




---

archive/issue_comments_448918.json:
```json
{
    "body": "**Commit:** [a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)",
    "created_at": "2018-02-09T16:53:26Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448918",
    "user": "https://github.com/fchapoton"
}
```

**Commit:** [a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)



---

archive/issue_comments_448919.json:
```json
{
    "body": "**Changing status** from needs_review to positive_review.",
    "created_at": "2018-02-09T21:41:10Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448919",
    "user": "https://github.com/tscrim"
}
```

**Changing status** from needs_review to positive_review.



---

archive/issue_comments_448920.json:
```json
{
    "body": "<a id='comment:2'></a>\nLGTM.",
    "created_at": "2018-02-09T21:41:10Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448920",
    "user": "https://github.com/tscrim"
}
```

<a id='comment:2'></a>
LGTM.



---

archive/issue_comments_448921.json:
```json
{
    "body": "**Reviewer:** Travis Scrimshaw",
    "created_at": "2018-02-09T21:41:10Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448921",
    "user": "https://github.com/tscrim"
}
```

**Reviewer:** Travis Scrimshaw



---

archive/issue_comments_448922.json:
```json
{
    "body": "**Changing status** from positive_review to needs_work.",
    "created_at": "2018-02-09T23:50:46Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448922",
    "user": "https://github.com/vbraun"
}
```

**Changing status** from positive_review to needs_work.



---

archive/issue_comments_448923.json:
```json
{
    "body": "<a id='comment:3'></a>\nMerge conflict",
    "created_at": "2018-02-09T23:50:46Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448923",
    "user": "https://github.com/vbraun"
}
```

<a id='comment:3'></a>
Merge conflict



---

archive/issue_comments_448924.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1 +1,69 @@\n-coming from future division\n+Future division made a doctest failure with the optional package plantri installed\n+\n+```\n+sage -t --long src/sage/graphs/graph_generators.py\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1408, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    [u for u in list(gen)]  # optional plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>\", line 1, in <module>\n+        [u for u in list(gen)]  # optional plantri\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n+        for G in graphs._read_planar_code(sp.stdout):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n+        edges_g[i + 1] += [i + 1] * (Ni / 2)\n+    TypeError: can't multiply sequence by non-int of type 'float'\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1439, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>\", line 1, in <module>\n+        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n+        for G in graphs._read_planar_code(sp.stdout):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n+        edges_g[i + 1] += [i + 1] * (Ni / 2)\n+    TypeError: can't multiply sequence by non-int of type 'float'\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1441, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>\", line 1, in <module>\n+        planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n+    NameError: name 'planar' is not defined\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1443, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar_sizes == dual_planar_sizes                      # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>\", line 1, in <module>\n+        planar_sizes == dual_planar_sizes                      # optional -- plantri\n+    NameError: name 'planar_sizes' is not defined\n+**********************************************************************\n+1 item had failures:\n+   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?\n+    [140 tests, 4 failures, 29.80 s]\n+```\n``````\n",
    "created_at": "2018-02-13T19:23:25Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448924",
    "user": "https://github.com/videlec"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1 +1,69 @@
-coming from future division
+Future division made a doctest failure with the optional package plantri installed
+
+```
+sage -t --long src/sage/graphs/graph_generators.py
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1408, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    [u for u in list(gen)]  # optional plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>", line 1, in <module>
+        [u for u in list(gen)]  # optional plantri
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
+        for G in graphs._read_planar_code(sp.stdout):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
+        edges_g[i + 1] += [i + 1] * (Ni / 2)
+    TypeError: can't multiply sequence by non-int of type 'float'
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1439, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>", line 1, in <module>
+        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
+        for G in graphs._read_planar_code(sp.stdout):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
+        edges_g[i + 1] += [i + 1] * (Ni / 2)
+    TypeError: can't multiply sequence by non-int of type 'float'
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1441, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar_sizes      = [g.size() for g in planar]         # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>", line 1, in <module>
+        planar_sizes      = [g.size() for g in planar]         # optional -- plantri
+    NameError: name 'planar' is not defined
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1443, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar_sizes == dual_planar_sizes                      # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>", line 1, in <module>
+        planar_sizes == dual_planar_sizes                      # optional -- plantri
+    NameError: name 'planar_sizes' is not defined
+**********************************************************************
+1 item had failures:
+   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?
+    [140 tests, 4 failures, 29.80 s]
+```
``````




---

archive/issue_comments_448925.json:
```json
{
    "body": "<a id='comment:5'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834\">d910d87</a></td><td><code>fix a division in graph_generators.py</code></td></tr></table>\n",
    "created_at": "2018-02-14T17:57:25Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448925",
    "user": "https://github.com/videlec"
}
```

<a id='comment:5'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834">d910d87</a></td><td><code>fix a division in graph_generators.py</code></td></tr></table>




---

archive/issue_comments_448926.json:
```json
{
    "body": "**Changing commit** from \"[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)\" to \"[d910d879adc9975475cd3f9fa385aeccada33834](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)\".",
    "created_at": "2018-02-14T17:57:25Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448926",
    "user": "https://github.com/videlec"
}
```

**Changing commit** from "[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)" to "[d910d879adc9975475cd3f9fa385aeccada33834](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)".



---

archive/issue_comments_448927.json:
```json
{
    "body": "**Changing status** from needs_work to needs_review.",
    "created_at": "2018-02-14T17:57:25Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448927",
    "user": "https://github.com/videlec"
}
```

**Changing status** from needs_work to needs_review.



---

archive/issue_comments_448928.json:
```json
{
    "body": "**Changing branch** from \"[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)\" to \"[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)\".",
    "created_at": "2018-02-14T17:57:25Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448928",
    "user": "https://github.com/videlec"
}
```

**Changing branch** from "[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)" to "[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)".



---

archive/issue_comments_448929.json:
```json
{
    "body": "**Changing status** from needs_review to positive_review.",
    "created_at": "2018-02-14T17:57:48Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448929",
    "user": "https://github.com/videlec"
}
```

**Changing status** from needs_review to positive_review.



---

archive/issue_comments_448930.json:
```json
{
    "body": "**Changing commit** from \"[d910d879adc9975475cd3f9fa385aeccada33834](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)\" to \"[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)\".",
    "created_at": "2018-02-14T17:58:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448930",
    "user": "https://github.com/videlec"
}
```

**Changing commit** from "[d910d879adc9975475cd3f9fa385aeccada33834](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)" to "[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)".



---

archive/issue_comments_448931.json:
```json
{
    "body": "<a id='comment:7'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc\">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>\n",
    "created_at": "2018-02-14T17:58:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448931",
    "user": "https://github.com/videlec"
}
```

<a id='comment:7'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>




---

archive/issue_comments_448932.json:
```json
{
    "body": "**Changing status** from positive_review to needs_work.",
    "created_at": "2018-02-14T17:58:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448932",
    "user": "https://github.com/videlec"
}
```

**Changing status** from positive_review to needs_work.



---

archive/issue_comments_448933.json:
```json
{
    "body": "**Changing branch** from \"[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)\" to \"[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)\".",
    "created_at": "2018-02-14T17:58:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448933",
    "user": "https://github.com/videlec"
}
```

**Changing branch** from "[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)" to "[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)".



---

archive/issue_comments_448934.json:
```json
{
    "body": "<a id='comment:8'></a>\nReplying to [vbraun](#comment%3A3):\n> Merge conflict\n\n\nSince this is fixing doctest related to an optional package, it would be nice to get it merged in the next beta...",
    "created_at": "2018-02-14T17:59:20Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448934",
    "user": "https://github.com/videlec"
}
```

<a id='comment:8'></a>
Replying to [vbraun](#comment%3A3):
> Merge conflict


Since this is fixing doctest related to an optional package, it would be nice to get it merged in the next beta...



---

archive/issue_comments_448935.json:
```json
{
    "body": "<a id='comment:9'></a>\nIt is supposed to have a conflict with Volker's private branch. But looking at the file there:\n\nhttps://github.com/vbraun/sage/commits/develop/src/sage/graphs/graph_generators.py\n\nI really do not see how there could be any conflict. This file was last modified 3 weeks ago.",
    "created_at": "2018-02-14T18:41:45Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448935",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:9'></a>
It is supposed to have a conflict with Volker's private branch. But looking at the file there:

https://github.com/vbraun/sage/commits/develop/src/sage/graphs/graph_generators.py

I really do not see how there could be any conflict. This file was last modified 3 weeks ago.



---

archive/issue_comments_448936.json:
```json
{
    "body": "**Changing status** from needs_work to positive_review.",
    "created_at": "2018-02-14T22:46:54Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448936",
    "user": "https://github.com/tscrim"
}
```

**Changing status** from needs_work to positive_review.



---

archive/issue_comments_448937.json:
```json
{
    "body": "<a id='comment:10'></a>\nLet's try it again then.",
    "created_at": "2018-02-14T22:46:54Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448937",
    "user": "https://github.com/tscrim"
}
```

<a id='comment:10'></a>
Let's try it again then.



---

archive/issue_events_070350.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-16T23:39:03Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/24698#event-70350"
}
```



---

archive/issue_comments_448938.json:
```json
{
    "body": "**Changing branch** from \"[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)\" to \"[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)\".",
    "created_at": "2018-02-16T23:39:03Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24698#issuecomment-448938",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)" to "[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)".
